---
title: uBuild Design Blocks
author: BRYuly
email: support@bayhomegoods.com
description: Website based on ubuild-jekyll theme on Forestry.io
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
